wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.10
    cli_version: 0.15.3
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: true
    start_time: 1693840417.204613
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 13
      - 23
      4: 3.10.10
      5: 0.15.3
      8:
      - 1
      - 2
      - 3
      - 5
